In [1]:
import pandas as pd

## Part 1 (2010–2020)

In [2]:
cpi_part1 = pd.read_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Raw Data\Inflation CPI YoY — Part 1 (2010-2020).csv"
)

In [3]:
cpi_part1.head()

,Dataset Name,Observation Date,Series Key,Series Display Name,Observation Value,Unit,Observation Status,Observation Status Comment,Sequence No.,Series name
0,Inflation Snapshot (Base Year: 2007-08),30-Apr-2020,TS_GP_RLS_CPI0708_M.P00010708,. General CPI (YoY),9.461951,Percent,Normal,NaN,10,"General CPI, an Inflation Measure (Year-on-Yea..."
1,Inflation Snapshot (Base Year: 2007-08),30-Apr-2020,TS_GP_RLS_CPI0708_M.P00020708,. WPI (YoY),7.342913,Percent,Normal,NaN,20,"WPI, an Inflation Measure (Year-on-Year basis)"
2,Inflation Snapshot (Base Year: 2007-08),30-Apr-2020,TS_GP_RLS_CPI0708_M.P00030708,. SPI (YoY),11.763063,Percent,Normal,NaN,30,"SPI, an Inflation Measure (Year-on-Year basis)"
3,Inflation Snapshot (Base Year: 2007-08),30-Apr-2020,TS_GP_RLS_CPI0708_M.P00040708,. General CPI (MoM),0.093679,Percent,Normal,NaN,40,"General CPI, an Inflation Measure (Month-on-Mo..."
4,Inflation Snapshot (Base Year: 2007-08),30-Apr-2020,TS_GP_RLS_CPI0708_M.P00050708,. WPI (MoM),-0.772792,Percent,Normal,NaN,50,"WPI, an Inflation Measure (Month-on-Month basis)"

In [8]:
cpi_part1.shape

(744, 10)

In [9]:
cpi_part1.columns

Index(['Dataset Name', 'Observation Date', 'Series Key', 'Series Display Name',
       'Observation Value', 'Unit', 'Observation Status',
       'Observation Status Comment', 'Sequence No.', 'Series name'],
      dtype='object')

In [10]:
cpi_part1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Dataset Name                744 non-null    object
 1   Observation Date            744 non-null    object
 2   Series Key                  744 non-null    object
 3   Series Display Name         744 non-null    object
 4   Observation Value           744 non-null    float64
 5   Unit                        744 non-null    object
 6   Observation Status          744 non-null    object
 7   Observation Status Comment  0 non-null      float64
 8   Sequence No.                744 non-null    int64
 9   Series name                 744 non-null    object
dtypes: float64(2), int64(1), object(7)
memory usage: 58.3+ KB

In [11]:
cpi_part1.isnull().sum()

Dataset Name                    0
Observation Date                0
Series Key                      0
Series Display Name             0
Observation Value               0
Unit                            0
Observation Status              0
Observation Status Comment    744
Sequence No.                    0
Series name                     0
dtype: int64

In [12]:
cpi_part1.duplicated().sum()

np.int64(0)

In [13]:
cpi_part1["Series name"].unique()

array(['General CPI, an Inflation Measure (Year-on-Year basis)',
       'WPI, an Inflation Measure (Year-on-Year basis)',
       'SPI, an Inflation Measure (Year-on-Year basis)',
       'General CPI, an Inflation Measure (Month-on-Month basis)',
       'WPI, an Inflation Measure (Month-on-Month basis)',
       'SPI, an Inflation Measure (Month-on-Month basis)'], dtype=object)

In [4]:
cpi_part1_filtered = cpi_part1[
    cpi_part1["Series name"] == "General CPI, an Inflation Measure (Year-on-Year basis)"
]

In [5]:
cpi_part1_filtered.head()

,Dataset Name,Observation Date,Series Key,Series Display Name,Observation Value,Unit,Observation Status,Observation Status Comment,Sequence No.,Series name
0,Inflation Snapshot (Base Year: 2007-08),30-Apr-2020,TS_GP_RLS_CPI0708_M.P00010708,. General CPI (YoY),9.461951,Percent,Normal,NaN,10,"General CPI, an Inflation Measure (Year-on-Yea..."
6,Inflation Snapshot (Base Year: 2007-08),31-Mar-2020,TS_GP_RLS_CPI0708_M.P00010708,. General CPI (YoY),10.743630,Percent,Normal,NaN,10,"General CPI, an Inflation Measure (Year-on-Yea..."
12,Inflation Snapshot (Base Year: 2007-08),29-Feb-2020,TS_GP_RLS_CPI0708_M.P00010708,. General CPI (YoY),12.032322,Percent,Normal,NaN,10,"General CPI, an Inflation Measure (Year-on-Yea..."
18,Inflation Snapshot (Base Year: 2007-08),31-Jan-2020,TS_GP_RLS_CPI0708_M.P00010708,. General CPI (YoY),13.070179,Percent,Normal,NaN,10,"General CPI, an Inflation Measure (Year-on-Yea..."
24,Inflation Snapshot (Base Year: 2007-08),31-Dec-2019,TS_GP_RLS_CPI0708_M.P00010708,. General CPI (YoY),12.421935,Percent,Normal,NaN,10,"General CPI, an Inflation Measure (Year-on-Yea..."

In [6]:
cpi_part1_filtered.shape

(124, 10)

In [7]:
cpi_part1_clean = cpi_part1_filtered[
    ["Observation Date", "Observation Value"]
].copy()

In [11]:
cpi_part1_clean.head()

           Date  Inflation_YoY
0   30-Apr-2020       9.461951
6   31-Mar-2020      10.743630
12  29-Feb-2020      12.032322
18  31-Jan-2020      13.070179
24  31-Dec-2019      12.421935

In [9]:
cpi_part1_clean.shape

(124, 2)

In [10]:
cpi_part1_clean.columns = ["Date", "Inflation_YoY"]

In [12]:
cpi_part1_clean["Date"] = pd.to_datetime(
    cpi_part1_clean["Date"],
    format="%d-%b-%Y"
)

In [13]:
cpi_part1_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 124 entries, 0 to 738
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           124 non-null    datetime64[ns]
 1   Inflation_YoY  124 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.9 KB

In [18]:
cpi_part1_clean = cpi_part1_clean.sort_values("Date")

In [19]:
cpi_part1_clean.head()

          Date  Inflation_YoY
738 2010-01-31      11.317190
732 2010-02-28      10.223615
726 2010-03-31      11.190818
720 2010-04-30      12.098930
714 2010-05-31      12.324415

In [20]:
cpi_part1_clean.tail()

         Date  Inflation_YoY
24 2019-12-31      12.421935
18 2020-01-31      13.070179
12 2020-02-29      12.032322
6  2020-03-31      10.743630
0  2020-04-30       9.461951

In [21]:
cpi_part1_clean.to_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Cleaned Data\Inflation_Part1_Cleaned.csv",
    index=False
)

## Part 2 (2016–2026)

In [22]:
cpi_part2 = pd.read_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Raw Data\Inflation CPI YoY — Part 2 (2016-2026).csv"
)

In [28]:
cpi_part2.head()

,Dataset Name,Observation Date,Series Key,Series Display Name,Observation Value,Unit,Observation Status,Observation Status Comment,Sequence No.,Series name
0,Inflation Snapshot (New Base: 2015-16),30-Jun-2026,TS_GP_PT_CPI_M.P00011516,. CPI-YoY-National,11.1,Percent,Normal,NaN,10,"National CPI, an Inflation Measure (Year-on-Ye..."
1,Inflation Snapshot (New Base: 2015-16),30-Jun-2026,TS_GP_PT_CPI_M.P00021516,............. Urban,11.2,Percent,Normal,NaN,20,"Urban CPI, an Inflation Measure (Year-on-Year ..."
2,Inflation Snapshot (New Base: 2015-16),30-Jun-2026,TS_GP_PT_CPI_M.P00041516,................... Food,8.2,Percent,Normal,NaN,30,"Urban Food CPI, an Inflation Measure (Year-on-..."
3,Inflation Snapshot (New Base: 2015-16),30-Jun-2026,TS_GP_PT_CPI_M.P00061516,................... Non-Food,13.1,Percent,Normal,NaN,40,"Urban Non-Food CPI, an Inflation Measure (Year..."
4,Inflation Snapshot (New Base: 2015-16),30-Jun-2026,TS_GP_PT_CPI_M.P00031516,............. Rural,10.9,Percent,Normal,NaN,50,"Rural CPI, an Inflation Measure (Year-on-Year ..."

In [29]:
cpi_part2.shape

(4440, 10)

In [31]:
cpi_part2.columns

Index(['Dataset Name', 'Observation Date', 'Series Key', 'Series Display Name',
       'Observation Value', 'Unit', 'Observation Status',
       'Observation Status Comment', 'Sequence No.', 'Series name'],
      dtype='object')

In [32]:
cpi_part2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4440 entries, 0 to 4439
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Dataset Name                4440 non-null   object
 1   Observation Date            4440 non-null   object
 2   Series Key                  4440 non-null   object
 3   Series Display Name         4440 non-null   object
 4   Observation Value           4440 non-null   float64
 5   Unit                        4440 non-null   object
 6   Observation Status          4440 non-null   object
 7   Observation Status Comment  60 non-null     float64
 8   Sequence No.                4440 non-null   int64
 9   Series name                 4440 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 347.0+ KB

In [33]:
cpi_part2.isnull().sum()

Dataset Name                     0
Observation Date                 0
Series Key                       0
Series Display Name              0
Observation Value                0
Unit                             0
Observation Status               0
Observation Status Comment    4380
Sequence No.                     0
Series name                      0
dtype: int64

In [34]:
cpi_part2.duplicated().sum()

np.int64(0)

In [35]:
cpi_part2["Series name"].unique()

array(['National CPI, an Inflation Measure (Year-on-Year basis)',
       'Urban CPI, an Inflation Measure (Year-on-Year basis)',
       'Urban Food CPI, an Inflation Measure (Year-on-Year basis)',
       'Urban Non-Food CPI, an Inflation Measure (Year-on-Year basis)',
       'Rural CPI, an Inflation Measure (Year-on-Year basis)',
       'Rural Food CPI, an Inflation Measure (Year-on-Year basis)',
       'Rural Non-Food CPI, an Inflation Measure (Year-on-Year basis)',
       'National CPI, an Inflation Measure (12-Months Moving average basis)',
       'Urban CPI, an Inflation Measure (12-Months Moving average basis)',
       'Urban Food CPI, an Inflation Measure (12-Months Moving average basis)',
       'Urban Non-Food CPI, an Inflation Measure (12-Months Moving average basis)',
       'Rural CPI, an Inflation Measure (12-Months Moving average basis)',
       'Rural Food CPI, an Inflation Measure (12-Months Moving average basis)',
       'Rural Non-Food CPI, an Inflation Measure (12-Months Moving average basis)',
       'National CPI, an Inflation Measure (Period average Since July basis)',
       'Urban CPI, an Inflation Measure (Period average Since July basis)',
       'Urban Food CPI, an Inflation Measure (Period average Since July basis)',
       'Urban Non-Food CPI, an Inflation Measure (Period average Since July basis)',
       'Rural CPI, an Inflation Measure (Period average Since July basis)',
       'Rural Food CPI, an Inflation Measure (Period average Since July basis)',
       'Rural Non-Food CPI, an Inflation Measure (Period average Since July basis)',
       'National CPI, an Inflation Measure (Month-on-Month basis)',
       'Urban CPI, an Inflation Measure (Month-on-Month basis)',
       'Urban Food CPI, an Inflation Measure (Month-on-Month basis)',
       'Urban Non-Food CPI, an Inflation Measure (Month-on-Month basis)',
       'Rural CPI, an Inflation Measure (Month-on-Month basis)',
       'Rural Food CPI, an Inflation Measure (Month-on-Month basis)',
       'Rural Non-Food CPI, an Inflation Measure (Month-on-Month basis)',
       'Urban NFNE Core Inflation, an Inflation Measure (Year-on-Year basis)',
       'Rural NFNE Core Inflation, an Inflation Measure (Year-on-Year basis)',
       'Urban NFNE Core Inflation, an Inflation Measure (12-Months Moving average basis)',
       'Rural NFNE Core Inflation, an Inflation Measure (12-Months Moving average basis)',
       'Urban NFNE Core Inflation, an Inflation Measure (Period average Since July basis)',
       'Rural NFNE Core Inflation, an Inflation Measure (Period average Since July basis)',
       'Urban NFNE Core Inflation, an Inflation Measure (Month-on-Month basis)',
       'Rural NFNE Core Inflation, an Inflation Measure (Month-on-Month basis)',
       'Urban Trimmed Core Inflation, an Inflation Measure (Year-on-Year basis)',
       'Rural Trimmed Core Inflation, an Inflation Measure (Year-on-Year basis)',
       'Urban Trimmed Core Inflation, an Inflation Measure (12-Months Moving average basis)',
       'Rural Trimmed Core Inflation, an Inflation Measure (12-Months Moving average basis)',
       'Urban Trimmed Core Inflation, an Inflation Measure (Period average Since July basis)',
       'Rural Trimmed Core Inflation, an Inflation Measure (Period average Since July basis)',
       'Urban Trimmed Core Inflation, an Inflation Measure (Month-on-Month basis)',
       'Rural Trimmed Core Inflation, an Inflation Measure (Month-on-Month basis)',
       'WPI, an Inflation Measure (Year-on-Year basis)',
       'WPI Food, an Inflation Measure (Year-on-Year basis)',
       'WPI Non-Food, an Inflation Measure (Year-on-Year basis)',
       'WPI, an Inflation Measure (12-Months Moving average basis)',
       'WPI Food, an Inflation Measure (12-Months Moving average basis)',
       'WPI Non-Food, an Inflation Measure (12-Months Moving average basis)',
       'WPI, an Inflation Measure (Period average Since July basis)',
       'WPI Food, an Inflation Measure (Period average Since July basis)',
       'WPI Non-Food, an Inflation Measure (Period average Since July basis)',
       'WPI, an Inflation Measure (Month-on-Month basis)',
       'WPI Food, an Inflation Measure (Month-on-Month basis)',
       'WPI Non-Food, an Inflation Measure (Month-on-Month basis)',
       'SPI, an Inflation Measure (Year-on-Year basis)',
       'SPI, an Inflation Measure (12-Months Moving average basis)',
       'SPI, an Inflation Measure (Period average Since July basis)',
       'SPI, an Inflation Measure (Month-on-Month basis)'], dtype=object)

In [36]:
cpi_part2_filtered = cpi_part2[
    cpi_part2["Series name"] ==
    "National CPI, an Inflation Measure (Year-on-Year basis)"
]

In [37]:
cpi_part2_filtered.shape

(74, 10)

In [38]:
cpi_part2_clean = cpi_part2_filtered[
    ["Observation Date", "Observation Value"]
].copy()

In [40]:
cpi_part2_clean.columns = [
    "Date",
    "Inflation_YoY"
]

In [41]:
cpi_part2_clean["Date"] = pd.to_datetime(
    cpi_part2_clean["Date"],
    format="%d-%b-%Y"
)

In [42]:
cpi_part2_clean = cpi_part2_clean.sort_values("Date")

In [43]:
cpi_part2_filtered.shape

(74, 10)

In [44]:
cpi_part2_clean["Date"].min()

Timestamp('2020-05-31 00:00:00')

In [45]:
cpi_part2_clean["Date"].max()

Timestamp('2026-06-30 00:00:00')

In [46]:
inflation = pd.concat(
    [cpi_part1_clean, cpi_part2_clean],
    ignore_index=True
)

In [47]:
inflation.shape

(198, 2)

In [48]:
inflation.head()

        Date  Inflation_YoY
0 2010-01-31      11.317190
1 2010-02-28      10.223615
2 2010-03-31      11.190818
3 2010-04-30      12.098930
4 2010-05-31      12.324415

In [49]:
inflation.tail()

          Date  Inflation_YoY
193 2026-02-28            7.0
194 2026-03-31            7.3
195 2026-04-30           10.9
196 2026-05-31           11.7
197 2026-06-30           11.1

In [50]:
inflation["Date"].duplicated().sum()

np.int64(0)

In [51]:
inflation.to_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Cleaned Data\Inflation_Cleaned.csv",
    index=False
)