In [1]:
import pandas as pd

In [2]:
petrol_prices = pd.read_csv(r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Raw Data\petrol_prices_pakistan_2010_2025.csv")

In [3]:
petrol_prices.head()

      Date  Petrol Price (PKR per litre)
0  2010-01                         66.36
1  2010-02                         66.36
2  2010-03                         69.03
3  2010-04                         71.21
4  2010-05                         72.96

In [4]:
petrol_prices.shape

(185, 2)

In [5]:
petrol_prices.columns

Index(['Date', 'Petrol Price (PKR per litre)'], dtype='object')

In [9]:
petrol_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date                          185 non-null    object
 1   Petrol Price (PKR per litre)  185 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.0+ KB

In [7]:
petrol_prices.isnull().sum()

Date                            0
Petrol Price (PKR per litre)    0
dtype: int64

In [8]:
petrol_prices.duplicated().sum()

np.int64(0)

In [10]:
petrol_prices.rename(
    columns={
        "Petrol Price (PKR per litre)": "Petrol_Price"
    },
    inplace=True
)

In [11]:
petrol_prices["Date"] = pd.to_datetime(
    petrol_prices["Date"],
    format="%Y-%m"
)

In [12]:
petrol_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          185 non-null    datetime64[ns]
 1   Petrol_Price  185 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 3.0 KB

In [35]:
petrol_prices.tail()

        Date  Petrol Price (PKR per litre)
180  2025-01                         281.3
181  2025-02                         284.5
182  2025-03                         287.2
183  2025-04                         289.1
184  2025-05                         292.0

In [14]:
petrol_prices_2 = pd.read_csv(r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Raw Data\Petrol Price.csv")

In [15]:
petrol_prices_2.head

<bound method NDFrame.head of       Period End   Islamabad  Rawalpindi  Gujranwala     Sialkot      Lahore  \
0         Weekly        PKR         PKR         PKR         PKR         PKR
1    09-Jul-2026  298.890000  298.790000  299.500000  299.740000  297.530000
2    02-Jul-2026  300.820000  300.800000  301.500000         303  299.780000
3    18-Jun-2026  375.250000  375.160000         376  376.240000  373.780000
4    11-Jun-2026  379.290000  379.190000         380         380  377.780000
..           ...         ...         ...         ...         ...         ...
638  31-Jan-2013  103.400000  103.400000  103.600000  105.600000  103.420000
639  24-Jan-2013  103.400000  103.400000  103.600000  105.600000  103.420000
640  17-Jan-2013  101.750000  101.750000  101.900000  103.900000  101.770000
641  10-Jan-2013  101.750000  101.750000  101.900000  103.900000  101.770000
642  03-Jan-2013  101.750000  101.750000  101.900000  103.900000  101.770000

     Faisalabad    Sargodha      Multan  Bahawalpur     Karachi   Hyderabad  \
0          PKR         PKR         PKR         PKR         PKR         PKR
1    298.750000  300.520000  299.040000  300.500000  298.750000  300.900000
2    300.720000  302.490000  301.050000  302.500000  300.720000  302.860000
3    375.140000  377.100000  375.460000  376.900000  375.140000  377.520000
4    379.140000  381.100000  379.470000  381.630000  379.140000  381.500000
..          ...         ...         ...         ...         ...         ...
638  103.500000  105.400000  103.450000         106  103.400000  104.700000
639  103.500000  105.400000  103.450000         106  103.400000  104.700000
640  101.900000  103.700000  101.800000  104.300000  101.700000  102.900000
641  101.900000  103.700000  101.800000  104.300000  101.700000  102.900000
642  101.900000  103.700000  101.800000  104.300000  101.700000  102.900000

         Sukkur     Larkana    Peshawar       Bannu      Quetta     Khuzdar  \
0          PKR         PKR         PKR         PKR         PKR         PKR
1    299.500000  299.500000  298.800000  300.400000  299.200000         299
2    300.720000  302.080000  300.700000  302.400000  301.170000  301.170000
3    375.140000  376.460000  375.100000  376.700000  375.170000  375.170000
4    379.200000  380.460000  379.100000  380.700000  379.170000  379.170000
..          ...         ...         ...         ...         ...         ...
638  103.500000  104.800000  103.500000         107  103.400000  104.450000
639  103.500000  104.800000  103.500000         107  103.400000  104.450000
640  101.900000  103.100000  101.800000  105.300000  102.800000  103.800000
641  101.900000  103.100000  101.800000  105.300000  102.800000  103.800000
642  101.900000  103.100000  101.800000  105.300000  102.800000  103.800000

       Pakistan
0          PKR
1    299.370000
2    301.440000
3    375.730000
4    379.770000
..          ...
638  104.270000
639  104.270000
640  102.710000
641  102.710000
642  102.710000

[643 rows x 19 columns]>

In [16]:
petrol_prices_2.shape

(643, 19)

In [18]:
petrol_prices_2.columns

Index(['Period End', 'Islamabad', 'Rawalpindi', 'Gujranwala', 'Sialkot',
       'Lahore', 'Faisalabad', 'Sargodha', 'Multan', 'Bahawalpur', 'Karachi',
       'Hyderabad', 'Sukkur', 'Larkana', 'Peshawar', 'Bannu', 'Quetta',
       'Khuzdar', 'Pakistan'],
      dtype='object')

In [19]:
petrol_prices_2.info

<bound method DataFrame.info of       Period End   Islamabad  Rawalpindi  Gujranwala     Sialkot      Lahore  \
0         Weekly        PKR         PKR         PKR         PKR         PKR
1    09-Jul-2026  298.890000  298.790000  299.500000  299.740000  297.530000
2    02-Jul-2026  300.820000  300.800000  301.500000         303  299.780000
3    18-Jun-2026  375.250000  375.160000         376  376.240000  373.780000
4    11-Jun-2026  379.290000  379.190000         380         380  377.780000
..           ...         ...         ...         ...         ...         ...
638  31-Jan-2013  103.400000  103.400000  103.600000  105.600000  103.420000
639  24-Jan-2013  103.400000  103.400000  103.600000  105.600000  103.420000
640  17-Jan-2013  101.750000  101.750000  101.900000  103.900000  101.770000
641  10-Jan-2013  101.750000  101.750000  101.900000  103.900000  101.770000
642  03-Jan-2013  101.750000  101.750000  101.900000  103.900000  101.770000

     Faisalabad    Sargodha      Multan  Bahawalpur     Karachi   Hyderabad  \
0          PKR         PKR         PKR         PKR         PKR         PKR
1    298.750000  300.520000  299.040000  300.500000  298.750000  300.900000
2    300.720000  302.490000  301.050000  302.500000  300.720000  302.860000
3    375.140000  377.100000  375.460000  376.900000  375.140000  377.520000
4    379.140000  381.100000  379.470000  381.630000  379.140000  381.500000
..          ...         ...         ...         ...         ...         ...
638  103.500000  105.400000  103.450000         106  103.400000  104.700000
639  103.500000  105.400000  103.450000         106  103.400000  104.700000
640  101.900000  103.700000  101.800000  104.300000  101.700000  102.900000
641  101.900000  103.700000  101.800000  104.300000  101.700000  102.900000
642  101.900000  103.700000  101.800000  104.300000  101.700000  102.900000

         Sukkur     Larkana    Peshawar       Bannu      Quetta     Khuzdar  \
0          PKR         PKR         PKR         PKR         PKR         PKR
1    299.500000  299.500000  298.800000  300.400000  299.200000         299
2    300.720000  302.080000  300.700000  302.400000  301.170000  301.170000
3    375.140000  376.460000  375.100000  376.700000  375.170000  375.170000
4    379.200000  380.460000  379.100000  380.700000  379.170000  379.170000
..          ...         ...         ...         ...         ...         ...
638  103.500000  104.800000  103.500000         107  103.400000  104.450000
639  103.500000  104.800000  103.500000         107  103.400000  104.450000
640  101.900000  103.100000  101.800000  105.300000  102.800000  103.800000
641  101.900000  103.100000  101.800000  105.300000  102.800000  103.800000
642  101.900000  103.100000  101.800000  105.300000  102.800000  103.800000

       Pakistan
0          PKR
1    299.370000
2    301.440000
3    375.730000
4    379.770000
..          ...
638  104.270000
639  104.270000
640  102.710000
641  102.710000
642  102.710000

[643 rows x 19 columns]>

In [20]:
petrol_prices_2.isnull().sum()

Period End    0
Islamabad     0
Rawalpindi    0
Gujranwala    0
Sialkot       0
Lahore        0
Faisalabad    0
Sargodha      0
Multan        0
Bahawalpur    0
Karachi       0
Hyderabad     0
Sukkur        0
Larkana       0
Peshawar      0
Bannu         0
Quetta        0
Khuzdar       0
Pakistan      0
dtype: int64

In [21]:
petrol_prices_2.duplicated().sum()

np.int64(0)

In [22]:
petrol_prices_2 = petrol_prices_2.iloc[1:].copy()

In [23]:
petrol_prices_2 = petrol_prices_2[
    ["Period End", "Pakistan"]
].copy()

In [24]:
petrol_prices_2.head()

    Period End    Pakistan
1  09-Jul-2026  299.370000
2  02-Jul-2026  301.440000
3  18-Jun-2026  375.730000
4  11-Jun-2026  379.770000
5  04-Jun-2026  383.760000

In [25]:
petrol_prices_2.columns = [
    "Date",
    "Petrol_Price"
]

In [26]:
petrol_prices_2["Date"] = pd.to_datetime(
    petrol_prices_2["Date"],
    format="%d-%b-%Y"
)

In [27]:
petrol_prices_2["Month"] = petrol_prices_2["Date"].dt.to_period("M")

In [28]:
petrol_prices_2.head()

        Date Petrol_Price    Month
1 2026-07-09   299.370000  2026-07
2 2026-07-02   301.440000  2026-07
3 2026-06-18   375.730000  2026-06
4 2026-06-11   379.770000  2026-06
5 2026-06-04   383.760000  2026-06

In [30]:
petrol_prices_2["Petrol_Price"] = pd.to_numeric(
    petrol_prices_2["Petrol_Price"],
    errors="coerce"
)

In [31]:
petrol_prices_2["Petrol_Price"].dtype

dtype('float64')

In [32]:
petrol_prices_2["Petrol_Price"].isnull().sum()

np.int64(0)

In [33]:
monthly_petrol = (
    petrol_prices_2
    .groupby("Month")["Petrol_Price"]
    .mean()
)

In [34]:
monthly_petrol.head

<bound method NDFrame.head of Month
2013-01    103.334000
2013-02    104.270000
2013-03    104.270000
2013-04    103.570000
2013-05     98.760000
              ...
2026-03    309.110000
2026-04    367.250000
2026-05    410.123333
2026-06    379.753333
2026-07    300.405000
Freq: M, Name: Petrol_Price, Length: 156, dtype: float64>

In [36]:
monthly_petrol = monthly_petrol.reset_index()

monthly_petrol = monthly_petrol[
    monthly_petrol["Month"] >= "2025-06-01"
]

In [37]:
petrol_prices.rename(
    columns={
        "Date": "Month",
        "Petrol Price (PKR per litre)": "Petrol_Price"
    },
    inplace=True
)

In [38]:
petrol_final = pd.concat(
    [petrol_prices, monthly_petrol],
    ignore_index=True
)

In [42]:
petrol_prices["Month"] = pd.to_datetime(petrol_prices["Month"])

In [43]:
monthly_petrol["Month"] = monthly_petrol["Month"].dt.to_timestamp()

In [44]:
petrol_final = pd.concat(
    [petrol_prices, monthly_petrol],
    ignore_index=True
)

petrol_final = petrol_final.sort_values("Month")
petrol_final.reset_index(drop=True, inplace=True)

In [46]:
petrol_final.to_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Cleaned Data\petrol_prices_clean.csv",
    index=False
)